### ISSUE TITLE
[Question] Can I use this library only to plot my truss structures?

### ISSUE THREAD

**Issue by Martin15135215** [cslotboom/planesections#13]
I want to plot my simple truss (2D) and space truss (3D). Can I use this library only for this use case? I don't need the analysis function etc.

In this line, is it possible to install planesections with pip without the dependencies openseespy

**Comment by cslotboom** [comment]
Hey, apologies, missed this. Right now, I have no plans to add the for the trusses. I'd consider adding a diagram feature for 2D trusses if there was enough demand. 3D trusses would be pretty difficult, Matplotlib does not work well in 3D.

About having no OpenSeespy, let me look into this. In the next version (1.2), I add the pynite solver which can be used instead of OpenSeespy. It would be nice to have OpenSeespy as an optional dependency. 

If you don't mind me asking, what is your issue with openseespy as a dependency? Are you worried about the license, or do you have issues with it because it's not pure python?

**Comment by Martin15135215** [comment]
I can well understand your difficulties with the visualization in 3D.

My reasoning was that if I create my own library and have this library as a dependency, it will automatically install OpenSeespy even if I don't need it.

**Comment by cslotboom** [comment]
Yeah I see - is the issue with OpenSeespy specifically, or just any analysis library?

**Comment by Martin15135215** [comment]
I am not a lawyer, however if I wanted to create an open-source python library that depends on planesetion. Do I need to also mention that there are some licence restriction even if I don't use planesection function, classes etc. that use openseespy?

**Comment by cslotboom** [comment]
Yeah I see. I also don't like the grey area OpenSees is in, you shouldn't have to worry about stuff like this.

From what I'm gathering the license is the significant thing. In the next version I'm considering making openseespy a optional install, and pynite the default solver. Pynite is opensource under a MIT license, so that would solve the licensing concerns.

I'll look into frame3dd! It would be nice to have a faster option than Pynite.

**Comment by cslotboom** [comment]
FYI, the latest release has made OpenSees an optional dependency. Let me know if this solves what you were looking for.

**Comment by cslotboom** [comment]
Consider taking a look at this library, it might fit your use case:
https://github.com/angelsolaorbaiceta/Mechanics/tree/master/structures

**Comment by Martin15135215** [comment]
Thank you for telling me about this helpful book! A beginner book in Python explaining how matrix, geometry etc are implemented was something I didn't know about.

**Comment by Martin15135215** [comment]
FYI: [CALFEM](https://github.com/CALFEM/calfem-python) is also a solver for beams etc.
